language: R
r: bioc-devel
bioc_required: true
bioc_use_devel: true
dist: bionic
r_github_packages: hadley/devtools
cache: packages
warnings_are_errors: false
after_script:
  - ls -lah
  - FILE=$(ls -1t *.tar.gz | head -n 1)
  - Rscript -e "library(BiocCheck); BiocCheck(\"${FILE}\")"
notifications:
  email:
    - oneillkza@gmail.com
