####################################################################################################
# makeBoxPlot -- creates boxplot of contigs included in the analysis vs those excluded
# @param chrTable  A data.frame consisting of chromosomes and lengths. Generated by makeChrTable()
# @param linkage.contigs A list of clustered contigs, generated by clusterContigs()
# @param saveFile='animal_boxplot.svg' location in which to save boxplot file
# @return an .svg file to the destination in saveLocation
# 
# @export
#
####################################################################################################


makeBoxPlot <- function(chrTable, linkage.contigs, sex.contigs=1, saveFile=FALSE)
{
	#Save a boxplot
	if(ncol(chrTable) > 2)
	{
		chrTable$length <- apply(chrTable, 1, function(x){as.numeric(x[3]) - as.numeric(x[2])})
	}

	includeLength <- chrTable[unlist(linkage.contigs),'length']/10^6
	#includeLength <- chrTable[unique(sub("_[0-9]*", '', unlist(linkage.contigs))), 'length']/10^6

	  if(length(sex.contigs) > 1)
	  {
	    sexLength <- chrTable[unlist(sex.contigs),'length']/10^6
	    includeLength <- c(includeLength, sexLength)
	  }
	excludeLength <- chrTable[setdiff(chrTable$chr,unlist(linkage.contigs)),'length']/10^6

	if(length(sex.contigs) > 1)
	{
	  seXclude <- chrTable[setdiff(chrTable$chr,unlist(linkage.contigs)),'length']/10^6
	  excludeLength <- c(excludeLength, seXclude)
	}
 	sumInclude <- round(sum(includeLength), digits=1)
	sumExclude <- round(sum(excludeLength), digits=1)
	percentInclude <- round(sumInclude / (sumInclude+sumExclude) *100, digits=1)

  if(saveFile != FALSE){png(paste(saveFile, '_boxplot.png'))}
	boxplot(includeLength, 
	excludeLength, 
	names=c(paste(sumInclude, ' Mb included (', percentInclude, '%)', sep="" ), paste(sumExclude, ' Mb excluded (', 100 - percentInclude, '%)', sep="") ),
	main='Length of contigs included in assembly vs excluded',
	ylab='Contig length (MB)')
	
	if(saveFile != FALSE){graphics.off()}
}