# Copyright (c) 2014, Mark Hills & Kieran O'Neill
# All rights reserved.

# Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:

#    * Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
#    * Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.

#THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.


####################################################################################################
# makeBoxPlot -- creates boxplot of contigs included in the analysis vs those excluded
# @param chrTable  A data.frame consisting of chromosomes and lengths. Generated by makeChrTable()
# @param linkage.contigs A list of clustered contigs, generated by clusterContigs()
# @param saveFile='animal_boxplot.svg' location in which to save boxplot file
# @return an .svg file to the destination in saveLocation
# 
# @export
#
####################################################################################################


makeBoxPlot <- function(chrTable, linkage.contigs, sex.contigs=1, saveFile=FALSE)
{
	#Save a boxplot
	if(ncol(chrTable) > 2)
	{
		chrTable$length <- apply(chrTable, 1, function(x){as.numeric(x[3]) - as.numeric(x[2])})
	}

	includeLength <- chrTable[which(chrTable[,1] %in% unlist(linkage.contigs)),'length']/10^6

	if(length(sex.contigs) > 1)
	{
	  sexLength <- chrTable[which(chrTable[,1] %in% unlist(sex.contigs)),'length']/10^6
	  includeLength <- c(includeLength, sexLength)
	}

	excludeLength <- chrTable[!(chrTable$chr %in% unlist(linkage.contigs)),'length']/10^6

	if(length(sex.contigs) > 1)
	{
	  seXclude <- chrTable[!(chrTable$chr %in% unlist(sex.contigs)),'length']/10^6
	  excludeLength <- c(excludeLength, seXclude)
	}
 	sumInclude <- round(sum(includeLength), digits=1)
	sumExclude <- round(sum(excludeLength), digits=1)
	percentInclude <- round(sumInclude / (sumInclude+sumExclude) *100, digits=1)

  if(saveFile != FALSE){png(paste(saveFile, '_boxplot.png'))}
	boxplot(includeLength, 
	excludeLength, 
	names=c(paste(sumInclude, ' Mb included (', percentInclude, '%)', sep="" ), paste(sumExclude, ' Mb excluded (', 100 - percentInclude, '%)', sep="") ),
	main='Length of contigs included in assembly vs excluded',
	ylab='Contig length (MB)')
	
	if(saveFile != FALSE){graphics.off()}
}